DELETE FROM Feature WHERE name='yADH1_promoter';
DELETE FROM Feature WHERE name='HIS4';
DELETE FROM Feature WHERE name='TRP1';
DELETE FROM Feature WHERE name='URA3';
DELETE FROM Feature WHERE name='HIS3_3UTR_terminator';
DELETE FROM Feature WHERE name='ura4_terminator';
DELETE FROM Feature WHERE name='yADH2_terminator';
DELETE FROM Feature WHERE name='GAL1_promoter';
DELETE FROM Feature WHERE name='HIS3';
DELETE FROM Feature WHERE name='LEU2';
UPDATE Feature SET organism_id=61756 WHERE name='3_AcPH';
UPDATE Feature SET organism_id=61756 WHERE name='Ac_3_flank';
UPDATE Feature SET organism_id=61756 WHERE name='Ac_5_flank';
UPDATE Feature SET organism_id=14522 WHERE name='CEN6_ARS4';
UPDATE Feature SET organism_id=24970 WHERE name='cosN';
UPDATE Feature SET organism_id=24890 WHERE name='CRE_NLS';
UPDATE Feature SET organism_id=14522 WHERE name='Gal4_AD';
UPDATE Feature SET organism_id=14522 WHERE name='Gal4_DBD';
UPDATE Feature SET organism_id=26471 WHERE name='HIV-1_5_LTR';
UPDATE Feature SET organism_id=26471 WHERE name='HIV-1_psi_pack';
UPDATE Feature SET organism_id=26471 WHERE name='HIV_Rev_NES';
UPDATE Feature SET organism_id=119495 WHERE name='lacY';
UPDATE Feature Set organism_id=119495 WHERE name='lacZ_a';
UPDATE Feature Set organism_id=24813 WHERE name='modSV40_late_16s_int';
UPDATE Feature SET organism_id=119495 WHERE name='ROP';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_3_splice';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_int';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_late_19s_int';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_lrgT';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_NLS';
UPDATE Feature SET organism_id=25101 WHERE name='T7_leader';
UPDATE Feature SET organism_id=25101 WHERE name='T7_transl_en_RBS';
UPDATE Feature SET organism_id=26471 WHERE name='truncHIV-1_3_LTR';
UPDATE Feature SET organism_id=43920 WHERE name='WPRE';
UPDATE Feature SET organism_id=24828 WHERE name='CaMVd35S_promoter';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_promoter';
UPDATE Feature SET organism_id=14522, description='Promoter for: Orotidine-5''-phosphate (OMP) decarboxylase, catalyzes the sixth enzymatic step in the de novo biosynthesis of pyrimidines, converting OMP into uridine monophosphate (UMP); converts 5-FOA into 5-fluorouracil, a toxic compound' WHERE name='URA3_promoter';
UPDATE Feature SET organism_id=119495 WHERE name='lacZ';
UPDATE Feature SET organism_id=24224 WHERE name='EBV_origin';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_origin';
UPDATE Feature SET organism_id=26702 WHERE name='3MoMuLV_LTR';
UPDATE Feature SET organism_id=26702 WHERE name='5MoMuLV_LTR';
UPDATE Feature SET organism_id=26471 WHERE name='RRE';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_enhancer';
UPDATE Feature SET organism_id=14522, description='terminator for: Cytochrome c, isoform 1; electron carrier of the mitochondrial intermembrane space that transfers electrons from ubiquinone-cytochrome c oxidoreductase to cytochrome c oxidase during cellular respiration' WHERE name='CYC1_terminator';
UPDATE Feature SET organism_id=24813 WHERE name='SV40_PA_terminator';
UPDATE Feature SET organism_id=14522, description='transcription termination sequence for URA4, which produces Dihydroorotase, catalyzes the third enzymatic step in the de novo biosynthesis of pyrimidines, converting carbamoyl-L-aspartate into dihydroorotate' WHERE name='ura4_terminator';
UPDATE Feature SET Feature.type_id=185 WHERE Feature.organism_id=14522 and Feature.type_id =82;
Delete * from Feature where length(Feature.sequence) < 20 and Feature.type_id != 46
DELETE * From Feature Where Feature.sequence = 'GACGTC' and Feature.name = 'BsaHI';
