/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.autogene.ui.cgview;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.autogene.algorithms.OligoMatch;
import org.autogene.core.bio.entities.Plasmid;
import org.autogene.ui.frames.BaseInternalFrame;

/**
 *
 * @author Robert
 */
public class ViewOligoMatches extends BaseInternalFrame {

    /**
     * Creates new form ViewOligoMatches
     */
    public ViewOligoMatches(Plasmid p) {
        initComponents();
        setTitle("View Oligo Matches");
        
        ArrayList<OligoMatch> om = p.getOligoMatches();
        Object[][] values = new Object[om.size()][5];
        for(int i = 0; i < om.size(); i++) {
            OligoMatch o = om.get(i);
            values[i][0] = o.getId();
            values[i][1] = o.getDescription();
            values[i][2] = (o.getStart()+"");
            values[i][3] = (o.getEnd() + "");
            values[i][4] = o.getDirection();
         }
        
        DefaultTableModel model = new DefaultTableModel(
            values,
            new String [] {
                "ID", "Description", "Start", "End", "Direction"
            }
        ) {
            

            public boolean isCellEditable(int rowIndex, int columnIndex) {
     
                return false;
            }
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
 

        };
        

        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Description", "Start", "End", "Direction"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
